version: '3.8'

services:
  # PHP-FPM Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wispr-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - /var/www/vendor/
      - /var/www/node_modules/
      - /var/www/admin/node_modules/
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    command: sh -c "php artisan serve --host=0.0.0.0 --port=8000"
    networks:
      - wispr-network

  # Node Service for React
  node:
    image: node:18-alpine
    container_name: wispr-node
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - /var/www/node_modules/
      - /var/www/admin/node_modules/
    command: sh -c "cd admin && npm ci && npm run dev"
    ports:
      - "5173:5173"
    networks:
      - wispr-network

networks:
  wispr-network:
    driver: bridge 